// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Y9s8V9MtZ8P6DgAy4Wv8lb42EVC4sUQ',
    appId: '1:865639163181:android:72e33f8fe364dbf3e95fa4',
    messagingSenderId: '865639163181',
    projectId: 'flutterfirebaseexam',
    databaseURL: 'https://flutterfirebaseexam-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebaseexam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkZU6RGrdJZ4HNuL_s2C2OweM2JLVgmEw',
    appId: '1:865639163181:ios:64a1fcf48f62c6a1e95fa4',
    messagingSenderId: '865639163181',
    projectId: 'flutterfirebaseexam',
    databaseURL: 'https://flutterfirebaseexam-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebaseexam.appspot.com',
    androidClientId: '865639163181-7qe6i7pfortarui2nh4s112hv6ea4kd6.apps.googleusercontent.com',
    iosClientId: '865639163181-jldmbu43u753q6pt7tb18bq0knjnjour.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseExample',
  );
}
